pub mod data;
pub mod gradient_check;
pub mod initialization;
pub mod loss;
pub mod model;
pub mod nn;
pub mod optimizer;
pub mod rng;
pub mod tensor;
pub mod trainer;

pub use data::MnistDataset;
pub use gradient_check::check_dense_weight_gradient;
pub use initialization::{Initialization, initialize_weights};
pub use loss::SoftmaxCrossEntropy;
pub use model::{TwoLayerAdamState, TwoLayerNetwork};
pub use nn::{Dense, ReLU};
pub use optimizer::{Adam, AdamState, Sgd};
pub use rng::Rng;
pub use tensor::Tensor;
pub use trainer::{Evaluation, evaluate, train_epoch_adam};
